# **Case Study: FIFA 2021 Dataset**

# Business Task

The goal of this case study is to identify the top performing players, and to analyze the relationship between player attributes and overall rating. 

Specifically, the task involves exploring a dataset of soccer player data and using statistical analysis to identify patterns and relationships between various player attributes and their overall performance.

Additionally, the study aims to provide insights into the best-performing players. This information can be used by coaches, team managers, and analysts to make data-driven decisions about player recruitment, training, and strategy.

# Description of all Data Sources

The data source for this case study is a Kaggle dataset titled "FIFA 21 Messy Raw Dataset for Cleaning & Exploring". The dataset can be found at [https://www.kaggle.com/datasets/yagunnersya/fifa-21-messy-raw-dataset-for-cleaning-exploring?select=fifa21\_raw\_data.csv](https://www.kaggle.com/datasets/yagunnersya/fifa-21-messy-raw-dataset-for-cleaning-exploring?select=fifa21_raw_data.csv).

The dataset is organized in a tabular format with 77 columns and over 18,979 rows. The columns contain a wide range of player attributes such as player names, nationality, age, positions, team contract details, physical attributes, skills, and overall stats. The dataset also includes some image data in the form of photo URLs for each player.

One potential issue with the data is the possibility of bias in the player ratings, which are determined by a combination of player performance and subjective assessments by game reviewers. Additionally, some players may have incomplete or missing data which could impact any analysis done on the dataset.

To verify the integrity of the data, it is recommended to conduct exploratory data analysis and data cleaning to identify any inconsistencies or errors in the data. This could involve checking for missing or duplicate values, outliers, or inconsistencies in the data.

Overall, this dataset can be useful for answering questions related to player performance and attributes in FIFA 21. However, it is important to be aware of potential biases and data quality issues when conducting any analysis.

# Documentation of Data Cleaning & manipulation of data

## Lookin at the data

In [137]:
SELECT TOP(10) * 
FROM [PortfolioProject].[dbo].[fifa21_raw_data]

photoUrl,LongName,playerUrl,Nationality,Positions,Name,Age,OVA,POT,Team_Contract,ID,Height,Weight,foot,BOV,BP,Growth,Joined,Loan_Date_End,Value,Wage,Release_Clause,Attacking,Crossing,Finishing,Heading_Accuracy,Short_Passing,Volleys,Skill,Dribbling,Curve,FK_Accuracy,Long_Passing,Ball_Control,Movement,Acceleration,Sprint_Speed,Agility,Reactions,Balance,Power,Shot_Power,Jumping,Stamina,Strength,Long_Shots,Mentality,Aggression,Interceptions,Positioning,Vision,Penalties,Composure,Defending,Marking,Standing_Tackle,Sliding_Tackle,Goalkeeping,GK_Diving,GK_Handling,GK_Kicking,GK_Positioning,GK_Reflexes,Total_Stats,Base_Stats,W_F,SM,A_W,D_W,IR,PAC,SHO,PAS,DRI,DEF,PHY,Hits
https://cdn.sofifa.com/players/158/023/21_60.png,Lionel Messi,http://sofifa.com/player/158023/lionel-messi/210005/,Argentina,RW ST CF,L. Messi,33,93,93,FC Barcelona 2004 ~ 2021,158023,"5'7""",159lbs,Left,93,RW,0,2004-07-01,N/A,€67.5M,€560K,€138.4M,429,85,95,70,91,88,470,96,93,94,91,96,451,91,80,91,94,95,389,86,68,72,69,94,347,44,40,93,95,75,96,91,32,35,24,54,6,11,15,14,8,2231,466,4 ★,4★,Medium,Low,5 ★,85,92,91,95,38,65,372
https://cdn.sofifa.com/players/020/801/21_60.png,C. Ronaldo dos Santos Aveiro,http://sofifa.com/player/20801/c-ronaldo-dos-santos-aveiro/210005/,Portugal,ST LW,Cristiano Ronaldo,35,92,92,Juventus 2018 ~ 2022,20801,"6'2""",183lbs,Right,92,ST,0,2018-07-10,N/A,€46M,€220K,€75.9M,437,84,95,90,82,86,414,88,81,76,77,92,431,87,91,87,95,71,444,94,95,84,78,93,353,63,29,95,82,84,95,84,28,32,24,58,7,11,15,14,11,2221,464,4 ★,5★,High,Low,5 ★,89,93,81,89,35,77,344
https://cdn.sofifa.com/players/200/389/21_60.png,Jan Oblak,http://sofifa.com/player/200389/jan-oblak/210005/,Slovenia,GK,J. Oblak,27,91,93,Atlético Madrid 2014 ~ 2023,200389,"6'2""",192lbs,Right,91,GK,2,2014-07-16,N/A,€75M,€125K,€159.4M,95,13,11,15,43,13,109,12,13,14,40,30,307,43,60,67,88,49,268,59,78,41,78,12,140,34,19,11,65,11,68,57,27,12,18,437,87,92,78,90,90,1413,489,3 ★,1★,Medium,Medium,3 ★,87,92,78,90,52,90,86
https://cdn.sofifa.com/players/192/985/21_60.png,Kevin De Bruyne,http://sofifa.com/player/192985/kevin-de-bruyne/210005/,Belgium,CAM CM,K. De Bruyne,29,91,91,Manchester City 2015 ~ 2023,192985,"5'11""",154lbs,Right,91,CAM,0,2015-08-30,N/A,€87M,€370K,€161M,407,94,82,55,94,82,441,88,85,83,93,92,398,77,76,78,91,76,408,91,63,89,74,91,408,76,66,88,94,84,91,186,68,65,53,56,15,13,5,10,13,2304,485,5 ★,4★,High,High,4 ★,76,86,93,88,64,78,163
https://cdn.sofifa.com/players/190/871/21_60.png,Neymar da Silva Santos Jr.,http://sofifa.com/player/190871/neymar-da-silva-santos-jr/210005/,Brazil,LW CAM,Neymar Jr,28,91,91,Paris Saint-Germain 2017 ~ 2022,190871,"5'9""",150lbs,Right,91,LW,0,2017-08-03,N/A,€90M,€270K,€166.5M,408,85,87,62,87,87,448,95,88,89,81,95,453,94,89,96,91,83,357,80,62,81,50,84,356,51,36,87,90,92,93,94,35,30,29,59,9,9,15,15,11,2175,451,5 ★,5★,High,Medium,5 ★,91,85,86,94,36,59,273
https://cdn.sofifa.com/players/188/545/21_60.png,Robert Lewandowski,http://sofifa.com/player/188545/robert-lewandowski/210005/,Poland,ST,R. Lewandowski,31,91,91,FC Bayern München 2014 ~ 2023,188545,"6'0""",176lbs,Right,91,ST,0,2014-07-01,N/A,€80M,€240K,€132M,423,71,94,85,84,89,407,85,79,85,70,88,407,77,78,77,93,82,420,89,84,76,86,85,391,81,49,94,79,88,88,96,35,42,19,51,15,6,12,8,10,2195,457,4 ★,4★,High,Medium,4 ★,78,91,78,85,43,82,182
https://cdn.sofifa.com/players/231/747/21_60.png,Kylian Mbappé,http://sofifa.com/player/231747/kylian-mbappe/210005/,France,ST LW RW,K. Mbappé,21,90,95,Paris Saint-Germain 2018 ~ 2022,231747,"5'10""",161lbs,Right,91,ST,5,2018-07-01,N/A,€105.5M,€160K,€203.1M,408,78,91,73,83,83,394,92,79,63,70,90,458,96,96,92,92,82,404,86,77,86,76,79,341,62,38,91,80,70,84,100,34,34,32,42,13,5,7,11,6,2147,466,4 ★,5★,High,Low,3 ★,96,86,78,91,39,76,646
https://cdn.sofifa.com/players/212/831/21_60.png,Alisson Ramses Becker,http://sofifa.com/player/212831/alisson-ramses-becker/210005/,Brazil,GK,Alisson,27,90,91,Liverpool 2018 ~ 2024,212831,"6'3""",201lbs,Right,90,GK,1,2018-07-19,N/A,€62.5M,€160K,€120.3M,114,17,13,19,45,20,138,27,19,18,44,30,268,56,47,40,88,37,240,64,52,32,78,14,140,27,11,13,66,23,65,50,15,19,16,439,86,88,85,91,89,1389,490,3 ★,1★,Medium,Medium,3 ★,86,88,85,89,51,91,79
https://cdn.sofifa.com/players/209/331/21_60.png,Mohamed Salah,http://sofifa.com/player/209331/mohamed-salah/210005/,Egypt,RW,M. Salah,28,90,90,Liverpool 2017 ~ 2023,209331,"5'9""",157lbs,Left,90,RW,0,2017-07-01,N/A,€78M,€250K,€144.3M,392,79,91,59,84,79,406,90,83,69,75,89,460,94,92,91,92,91,393,80,69,85,75,84,376,63,55,91,84,83,90,122,38,43,41,62,14,14,9,11,14,2211,470,3 ★,4★,High,Medium,3 ★,93,86,81,90,45,75,164
https://cdn.sofifa.com/players/208/722/21_60.png,Sadio Mané,http://sofifa.com/player/208722/sadio-mane/210005/,Senegal,LW,S. Mané,28,90,90,Liverpool 2016 ~ 2023,208722,"5'9""",152lbs,Right,90,LW,0,2016-07-01,N/A,€78M,€250K,€144.3M,410,76,90,84,85,75,391,91,76,64,71,89,460,95,93,93,93,86,406,84,86,88,70,78,358,75,35,92,85,71,84,122,42,42,38,56,10,10,15,7,14,2203,469,4 ★,4★,High,Medium,3 ★,94,85,80,90,44,76,170

In [211]:
-- Counting Rows
SELECT COUNT(*) FROM [PortfolioProject].[dbo].[fifa21_raw_data];

(No column name)
18979

In [214]:
-- Checking for Duplicate Rows
SELECT DISTINCT COUNT(*) FROM [PortfolioProject].[dbo].[fifa21_raw_data];
-- There aren't any Duplicated rows

(No column name)
18979

### Initially looking at the data, we identified the following tasks that need to be done before conducting data analysis on the FIFA21 raw data:

- Remove unnecessary columns: photoUrl, playerUrl, and Name (redundant since the dataset contains LongName).
- Split Positions column into first position, second position, and third position. Necessary to identify the top-performing players for each position.
- Split Team\_Contract column into team and contract. Allow us to identify the top-performing players for each Team.
- Split Contract column into start contract and end contract. In case the end contract is null, it will take the loan date values. 
- Format Weight, Value, Wage, Release\_Clause, W\_F, SM, and IR into numeric format.
- Format start contract and end contract into date format.
- Create a working table named fifa21\_clean\_data. 
- Create a final table named fifa21\_data. Table will be using for the analysis

## Data Wrangling

### Creating a working table and Removing Irrelevant Columns

In [138]:
-- Creating new table, for data wrangling from fifa21_raw_data
SELECT *
INTO [PortfolioProject].[dbo].[fifa21_clean_data]
FROM [PortfolioProject].[dbo].[fifa21_raw_data]

: Msg 2714, Level 16, State 6, Line 2
There is already an object named 'fifa21_clean_data' in the database.

In [139]:
-- Removing Irrelevant columns: photoUrl, playerUrl, Name
ALTER TABLE [PortfolioProject].[dbo].[fifa21_clean_data]
DROP COLUMN [photoUrl], [playerUrl], [Name];

: Msg 4924, Level 16, State 1, Line 2
ALTER TABLE DROP COLUMN failed because column 'photoUrl' does not exist in table 'fifa21_clean_data'.

### Creating New Columns for Positions: Position 1, Position 2 and Position 3

In [140]:
-- Splitting Positions into Position1, Position2, Position3 
ALTER TABLE [PortfolioProject].[dbo].[fifa21_clean_data]
ADD Position1 VARCHAR(50),
    Position2 VARCHAR(50),
    Position3 VARCHAR(50)

: Msg 2705, Level 16, State 4, Line 2
Column names in each table must be unique. Column name 'Position1' in table 'PortfolioProject.dbo.fifa21_clean_data' is specified more than once.

In [141]:
-- Updating Position 1, Position 2, and Position 3 with values using SUBSTRING and CHARINDEX functions
UPDATE [PortfolioProject].[dbo].[fifa21_clean_data]
SET Position1 = SUBSTRING(Positions, 1, CHARINDEX(' ', Positions + ' ') - 1),
    Position2 = CASE 
                   WHEN LEN(Positions) - LEN(REPLACE(Positions, ' ', '')) >= 1 THEN 
                       SUBSTRING(Positions, CHARINDEX(' ', Positions + ' ') + 1, CHARINDEX(' ', Positions + ' ', CHARINDEX(' ', Positions + ' ') + 1) - CHARINDEX(' ', Positions + ' ') - 1)
                   ELSE NULL
                END,
    Position3 = CASE 
                   WHEN LEN(Positions) - LEN(REPLACE(Positions, ' ', '')) = 2 THEN 
                       SUBSTRING(Positions, CHARINDEX(' ', Positions + ' ', CHARINDEX(' ', Positions + ' ') + 1) + 1, LEN(Positions))
                   ELSE NULL
                END

### Extracting Contract from the Column Team\_Contract

In [142]:
-- Pulling out Contract from Team_contract
SELECT TOP(10) Team_Contract,
    CASE WHEN CHARINDEX(' 20', Team_Contract) > 0
         THEN SUBSTRING(Team_Contract, CHARINDEX('20', Team_Contract),11)
         ELSE ''
    END AS Contract
FROM [PortfolioProject].[dbo].[fifa21_clean_data]

Team_Contract,Contract
AZ Alkmaar 2017 ~ 2023,2017 ~ 2023
AZ Alkmaar 2017 ~ 2021,2017 ~ 2021
Monterrey 2015 ~ 2022,2015 ~ 2022
Monterrey 2016 ~ 2021,2016 ~ 2021
VfL Wolfsburg 2016 ~ 2023,2016 ~ 2023
Borussia Mönchengladbach 2010 ~ 2022,2010 ~ 2022
FC Porto 2015 ~ 2021,2015 ~ 2021
Newcastle United 2020 ~ 2024,2020 ~ 2024
RC Celta 2009 ~ 2023,2009 ~ 2023
Deportivo Alavés 2014 ~ 2022,2014 ~ 2022

In [143]:
-- Adding Contract column to table
ALTER TABLE [PortfolioProject].[dbo].[fifa21_clean_data]
ADD Contract Nvarchar(50);

: Msg 2705, Level 16, State 4, Line 2
Column names in each table must be unique. Column name 'Contract' in table 'PortfolioProject.dbo.fifa21_clean_data' is specified more than once.

In [144]:
-- Setting Contract Value
UPDATE [PortfolioProject].[dbo].[fifa21_clean_data]
SET Contract =  CASE WHEN CHARINDEX(' 20', Team_Contract) > 0
         THEN SUBSTRING(Team_Contract, CHARINDEX('20', Team_Contract),11)
         ELSE ''
    END

### Splitting Contract into Start Contract and End Contract

In [145]:
-- Splitting contract into Start_Contract an End Contract
SELECT TOP(10)
    contract,
    LEFT(contract, 4) AS Start_Contract,
    RIGHT(contract, 4) AS End_Contract
FROM [PortfolioProject].[dbo].[fifa21_clean_data]

contract,Start_Contract,End_Contract
2017 ~ 2023,2017,2023
2017 ~ 2021,2017,2021
2015 ~ 2022,2015,2022
2016 ~ 2021,2016,2021
2016 ~ 2023,2016,2023
2010 ~ 2022,2010,2022
2015 ~ 2021,2015,2021
2020 ~ 2024,2020,2024
2009 ~ 2023,2009,2023
2014 ~ 2022,2014,2022

In [146]:
-- Adding Columns, Start Contract and End Contract 
ALTER TABLE [PortfolioProject].[dbo].[fifa21_clean_data]
ADD Start_Contract NVARCHAR(50);

ALTER TABLE [PortfolioProject].[dbo].[fifa21_clean_data]
ADD End_Contract NVARCHAR(50);

: Msg 2705, Level 16, State 4, Line 2
Column names in each table must be unique. Column name 'Start_Contract' in table 'PortfolioProject.dbo.fifa21_clean_data' is specified more than once.

In [147]:
-- Setting Values for Start Contract and End Contract 
UPDATE [PortfolioProject].[dbo].[fifa21_clean_data]
SET Start_Contract = LEFT(contract, 4)

UPDATE [PortfolioProject].[dbo].[fifa21_clean_data]
SET End_Contract = RIGHT(contract, 4)

### Cleaning and Formatting Start Contract and End Contract as Date

In [148]:
-- Looking at End_Contract 
SELECT TOP(10) Start_Contract, End_Contract, Team_Contract, Loan_Date_End, Team
FROM [PortfolioProject].[dbo].[fifa21_clean_data]
ORDER BY Start_Contract DESC;
-- End Contract have a string 'Loa'. That stands for Loan_Date_End
-- We are going to substitute Loa for values in Loan_Date_End

: Msg 207, Level 16, State 1, Line 2
Invalid column name 'Team'.

In [149]:
-- cleaning column with CASE function targetting 'Loa'
SELECT TOP(10)
    Start_Contract, 
    CASE WHEN End_Contract = 'Loa' THEN '' ELSE CONVERT(varchar, TRY_CONVERT(date, End_Contract), 101) END AS End_Contract, 
    Team_Contract, 
    Loan_Date_End, 
    Team
FROM [PortfolioProject].[dbo].[fifa21_clean_data]
ORDER BY Start_Contract DESC;

: Msg 207, Level 16, State 1, Line 7
Invalid column name 'Team'.

In [150]:
-- Updating End Contract with new value sustituting 'Loa' with Loan Date End
UPDATE [PortfolioProject].[dbo].[fifa21_clean_data]
SET End_Contract = 
    CASE 
        WHEN End_Contract = 'Loa' THEN '' 
        WHEN End_Contract IS NULL THEN CONVERT(varchar, TRY_CONVERT(date, Loan_Date_End), 101)
        ELSE CONVERT(varchar, TRY_CONVERT(date, End_Contract), 101) 
    END

UPDATE [PortfolioProject].[dbo].[fifa21_clean_data]
SET End_Contract = NULL
WHERE YEAR(End_Contract) < 2000

In [151]:
-- Changing Format for End Contract
UPDATE [PortfolioProject].[dbo].[fifa21_clean_data]
SET End_Contract = CONVERT(varchar, TRY_CONVERT(date, CASE WHEN End_Contract IS NULL THEN Loan_Date_End ELSE End_Contract END), 101)

In [152]:
--Cleaning and Changing Format for Start_Contract
SELECT TOP(10)
    Start_Contract, 
    CONVERT(varchar, TRY_CONVERT(date, CASE WHEN End_Contract IS NULL THEN Loan_Date_End ELSE End_Contract END), 101) AS End_Contract, 
    Team_Contract, 
    Loan_Date_End, 
    Team
FROM [PortfolioProject].[dbo].[fifa21_clean_data]
ORDER BY Start_Contract DESC

: Msg 207, Level 16, State 1, Line 2
Invalid column name 'Team'.

In [153]:
-- Using Cast function to convert value to date
SELECT TOP(10) Start_Contract, CAST(Start_contract AS DATE) 
FROM [PortfolioProject].[dbo].[fifa21_clean_data]

Start_Contract,(No column name)
2017,2017-01-01
2017,2017-01-01
2015,2015-01-01
2016,2016-01-01
2016,2016-01-01
2010,2010-01-01
2015,2015-01-01
2020,2020-01-01
2009,2009-01-01
2014,2014-01-01

In [154]:
-- Updating type for Start Contract, formatting as Date
UPDATE [PortfolioProject].[dbo].[fifa21_clean_data]
SET Start_Contract = CAST(Start_contract AS DATE) 

UPDATE [PortfolioProject].[dbo].[fifa21_clean_data]
SET Start_Contract = NULL
WHERE YEAR(Start_Contract) < 2000

### Extracting Team from the Column Team\_Contract

In [155]:
-- Pulling out Team from Team_contract
SELECT TOP(10) Team_Contract,
    CASE 
        WHEN CHARINDEX(' 20', Team_Contract) > 0
            THEN SUBSTRING(Team_Contract, 5, CHARINDEX('20', Team_Contract) - 6)
        WHEN CHARINDEX(' 20', Team_Contract) = 0
            THEN SUBSTRING(Team_Contract, 3, LEN(Team_Contract)-4)
        ELSE ''
    END AS Team
FROM [PortfolioProject].[dbo].[fifa21_clean_data]

Team_Contract,Team
AZ Alkmaar 2017 ~ 2023,AZ Alkmaar
AZ Alkmaar 2017 ~ 2021,AZ Alkmaar
Monterrey 2015 ~ 2022,Monterrey
Monterrey 2016 ~ 2021,Monterrey
VfL Wolfsburg 2016 ~ 2023,VfL Wolfsburg
Borussia Mönchengladbach 2010 ~ 2022,Borussia Mönchengladbach
FC Porto 2015 ~ 2021,FC Porto
Newcastle United 2020 ~ 2024,Newcastle United
RC Celta 2009 ~ 2023,RC Celta
Deportivo Alavés 2014 ~ 2022,Deportivo Alavés

In [156]:
-- Creating Team column 
ALTER TABLE [PortfolioProject].[dbo].[fifa21_clean_data]
ADD Team Nvarchar(50);

In [157]:
-- Setting Team values
UPDATE [PortfolioProject].[dbo].[fifa21_clean_data]
SET Team =  CASE 
        WHEN CHARINDEX(' 20', Team_Contract) > 0
            THEN SUBSTRING(Team_Contract, 5, CHARINDEX('20', Team_Contract) - 6)
        WHEN CHARINDEX(' 20', Team_Contract) = 0
            THEN SUBSTRING(Team_Contract, 3, LEN(Team_Contract)-4)
        ELSE ''
    END

In [158]:
-- Looking at data. 
SELECT TOP (30) Team_Contract, Loan_Date_End, Team
FROM [PortfolioProject].[dbo].[fifa21_clean_data]
ORDER BY Loan_Date_End DESC

-- Team wasnt fully extract for case where Loan_Date_End isnt NA

Team_Contract,Loan_Date_End,Team
"Derry City Nov 30, 2020 On Loan","Nov 30, 2020","Derry City Nov 30,"
"Cork City Nov 30, 2020 On Loan","Nov 30, 2020","Cork City Nov 30,"
"Cork City Nov 30, 2020 On Loan","Nov 30, 2020","Cork City Nov 30,"
"Shamrock Rovers Nov 30, 2020 On Loan","Nov 30, 2020","Shamrock Rovers Nov 30,"
"St. Patrick's Athletic Nov 30, 2020 On Loan","Nov 30, 2020","St. Patrick's Athletic Nov 30,"
"Finn Harps Nov 30, 2020 On Loan","Nov 30, 2020","Finn Harps Nov 30,"
"Cork City Nov 30, 2020 On Loan","Nov 30, 2020","Cork City Nov 30,"
"Sangju Sangmu FC Nov 27, 2021 On Loan","Nov 27, 2021","Sangju Sangmu FC Nov 27,"
"Sangju Sangmu FC Nov 27, 2021 On Loan","Nov 27, 2021","Sangju Sangmu FC Nov 27,"
"Sangju Sangmu FC Nov 27, 2021 On Loan","Nov 27, 2021","Sangju Sangmu FC Nov 27,"
"Sangju Sangmu FC Nov 27, 2021 On Loan","Nov 27, 2021","Sangju Sangmu FC Nov 27,"
"Sangju Sangmu FC Nov 27, 2021 On Loan","Nov 27, 2021","Sangju Sangmu FC Nov 27,"
"Sangju Sangmu FC Nov 27, 2021 On Loan","Nov 27, 2021","Sangju Sangmu FC Nov 27,"
"Sangju Sangmu FC Nov 22, 2020 On Loan","Nov 22, 2020","Sangju Sangmu FC Nov 22,"
"Sangju Sangmu FC Nov 22, 2020 On Loan","Nov 22, 2020","Sangju Sangmu FC Nov 22,"
"Sangju Sangmu FC Nov 22, 2020 On Loan","Nov 22, 2020","Sangju Sangmu FC Nov 22,"
"Sangju Sangmu FC Nov 22, 2020 On Loan","Nov 22, 2020","Sangju Sangmu FC Nov 22,"
"Sangju Sangmu FC Nov 22, 2020 On Loan","Nov 22, 2020","Sangju Sangmu FC Nov 22,"
Tigres U.A.N.L. 2017 ~ 2023,N/A,Tigres U.A.N.L.
River Plate 2019 ~ 2022,N/A,River Plate
Club Atlético Lanús 2013 ~ 2022,N/A,Club Atlético Lanús
Lazio 2011 ~ 2021,N/A,Lazio
West Ham United 2016 ~ 2023,N/A,West Ham United
Eintracht Frankfurt 2019 ~ 2022,N/A,Eintracht Frankfurt
Burnley 2017 ~ 2023,N/A,Burnley
Athletic Club de Bilbao 2009 ~ 2021,N/A,Athletic Club de Bilbao
Borussia Dortmund 2018 ~ 2021,N/A,Borussia Dortmund
West Ham United 2015 ~ 2021,N/A,West Ham United
Al Nassr 2020 ~ 2021,N/A,Al Nassr
Tigres U.A.N.L. 2016 ~ 2022,N/A,Tigres U.A.N.L.

In [159]:
-- In order to fully extract Team from Team_Contract we need to take into account Loan_Date_End N/A values
SELECT TOP(30)
    Start_Contract, 
    End_Contract, 
    Team_Contract, 
    CASE 
        WHEN Loan_Date_End != 'N/A' 
        THEN SUBSTRING(Team, 1, LEN(Team) - 8)
        ELSE Team 
    END AS Team
FROM 
    [PortfolioProject].[dbo].[fifa21_clean_data]
ORDER BY 
    Start_Contract DESC

Start_Contract,End_Contract,Team_Contract,Team
2023-01-01,06/30/2023,"Beerschot AC Jun 30, 2023 On Loan",Beerschot AC
2022-01-01,06/30/2022,"Eintracht Frankfurt Jun 30, 2022 On Loan",Eintracht Frankfurt
2022-01-01,06/30/2022,"PSV Jun 30, 2022 On Loan",PSV
2022-01-01,06/30/2022,"Borussia Dortmund Jun 30, 2022 On Loan",Borussia Dortmund
2022-01-01,06/30/2022,"Royal Antwerp FC Jun 30, 2022 On Loan",Royal Antwerp FC
2022-01-01,06/30/2022,"SD Ponferradina Jun 30, 2022 On Loan",SD Ponferradina
2022-01-01,06/30/2022,"SC Heerenveen Jun 30, 2022 On Loan",SC Heerenveen
2022-01-01,05/31/2022,"Alanyaspor May 31, 2022 On Loan",Alanyaspor
2022-01-01,06/30/2022,"SL Benfica Jun 30, 2022 On Loan",SL Benfica
2022-01-01,06/30/2022,"Sporting CP Jun 30, 2022 On Loan",Sporting CP
2022-01-01,06/30/2022,"Genoa Jun 30, 2022 On Loan",Genoa
2022-01-01,06/30/2022,"SSV Jahn Regensburg Jun 30, 2022 On Loan",SSV Jahn Regensburg
2022-01-01,05/31/2022,"Alanyaspor May 31, 2022 On Loan",Alanyaspor
2022-01-01,06/30/2022,"VfL Osnabrück Jun 30, 2022 On Loan",VfL Osnabrück
2022-01-01,06/30/2022,"1. FC Nürnberg Jun 30, 2022 On Loan",1. FC Nürnberg
2022-01-01,06/30/2022,"ADO Den Haag Jun 30, 2022 On Loan",ADO Den Haag
2022-01-01,06/30/2022,"1. FC Magdeburg Jun 30, 2022 On Loan",1. FC Magdeburg
2022-01-01,06/30/2022,"KV Oostende Jun 30, 2022 On Loan",KV Oostende
2021-01-01,06/30/2021,"Sampdoria Jun 30, 2021 On Loan",Sampdoria
2021-01-01,06/30/2021,"Benevento Jun 30, 2021 On Loan",Benevento
2021-01-01,06/30/2021,"Deportivo Alavés Jun 30, 2021 On Loan",Deportivo Alavés
2021-01-01,06/30/2021,"TSG 1899 Hoffenheim Jun 30, 2021 On Loan",TSG 1899 Hoffenheim
2021-01-01,06/30/2021,"Fulham Jun 30, 2021 On Loan",Fulham
2021-01-01,01/30/2021,"Manchester United Jan 30, 2021 On Loan",Manchester United
2021-01-01,06/30/2021,"Celtic Jun 30, 2021 On Loan",Celtic
2021-01-01,06/30/2021,"Al Wehda Jun 30, 2021 On Loan",Al Wehda
2021-01-01,06/30/2021,"FC Schalke 04 Jun 30, 2021 On Loan",FC Schalke 04
2021-01-01,06/30/2021,"RC Celta Jun 30, 2021 On Loan",RC Celta
2021-01-01,06/30/2021,"Al Shabab Jun 30, 2021 On Loan",Al Shabab
2021-01-01,06/30/2021,"Parma Jun 30, 2021 On Loan",Parma

In [160]:
-- Setting Team Values taking into account Loan_Date_End
UPDATE [PortfolioProject].[dbo].[fifa21_clean_data]
SET Team = CASE 
        WHEN Loan_Date_End != 'N/A' 
        THEN SUBSTRING(Team, 1, LEN(Team) - 8)
        ELSE Team 
    END

## Formatting Weigh as Integer, by removing "lb"

In [161]:
-- Removing lbs from Weight and Formatting as integer
SELECT TOP(10) Weight, REPLACE(Weight, 'lbs', '')
FROM [PortfolioProject].[dbo].[fifa21_clean_data]

Weight,(No column name)
154lbs,154
154lbs,154
172lbs,172
163lbs,163
170lbs,170
154lbs,154
172lbs,172
146lbs,146
152lbs,152
176lbs,176

In [162]:
-- Adding Column Weight_lbs
ALTER TABLE [PortfolioProject].[dbo].[fifa21_clean_data]
ADD Weight_lbs int;

In [163]:
-- Setting Column Weight_lbs Values
UPDATE [PortfolioProject].[dbo].[fifa21_clean_data]
SET Weight_lbs = REPLACE(Weight, 'lbs', '')

## Formatting Value as Float, by removing "€", "M" and "K"

In [164]:
-- Removing Euro an M sign from Value and Formatting as Float
SELECT TOP(10) Value, REPLACE(REPLACE(Value, '€', ''), 'M', '')
FROM [PortfolioProject].[dbo].[fifa21_clean_data]

Value,(No column name)
€12M,12
€10.5M,10.5
€10.5M,10.5
€8M,8
€9M,9
€10M,10
€10.5M,10.5
€10.5M,10.5
€8.5M,8.5
€8.5M,8.5

In [165]:
-- Adding Column Value_M_E to table
ALTER TABLE [PortfolioProject].[dbo].[fifa21_clean_data]
ADD Value_M_E VARCHAR(50);

In [166]:
-- Setting Value_M_E values
UPDATE [PortfolioProject].[dbo].[fifa21_clean_data]
SET Value_M_E = REPLACE(REPLACE(Value, '€', ''), 'M', '')

In [167]:
-- Formatting Value_M_E as FLOAT
SELECT TOP(10) Value_M_E = CAST(REPLACE(Value_M_E, ',', '') AS FLOAT)
FROM [PortfolioProject].[dbo].[fifa21_clean_data]
WHERE Value_M_E IS NOT NULL
AND TRY_CONVERT(FLOAT, REPLACE(Value_M_E, ',', '')) IS NOT NULL;

Value_M_E
12
10.5
10.5
8
9
10
10.5
10.5
8.5
8.5

In [168]:
-- Setting type as FLOAT
UPDATE [PortfolioProject].[dbo].[fifa21_clean_data]
SET Value_M_E = CAST(REPLACE(Value_M_E, ',', '') AS FLOAT)
WHERE Value_M_E IS NOT NULL
AND TRY_CONVERT(FLOAT, REPLACE(Value_M_E, ',', '')) IS NOT NULL;

In [169]:
SELECT TOP(10) Value_M_E, Value
FROM [PortfolioProject].[dbo].[fifa21_clean_data]
ORDER BY Value_M_E DESC
-- The transformation didnt work for cases where K was present instead of M as non numeric

Value_M_E,Value
975K,€975K
975K,€975K
975K,€975K
975K,€975K
975K,€975K
975K,€975K
975K,€975K
975K,€975K
975K,€975K
975K,€975K

In [170]:
-- Account for cases where value include "K"
SELECT TOP(10)
    CASE 
        WHEN Value_M_E LIKE '%[^0-9.]%' 
        THEN CAST(SUBSTRING(Value_M_E, 1, LEN(Value_M_E)-1) AS DECIMAL(10,2))/1000
        ELSE CAST(Value_M_E AS DECIMAL(10,2))
    END AS Value_M_E,
    Value
FROM 
    [PortfolioProject].[dbo].[fifa21_clean_data]
ORDER BY 
    Value_M_E

Value_M_E,Value
0.0000000,€0
0.0000000,€0
0.0000000,€0
0.0000000,€0
0.0000000,€0
0.0000000,€0
0.0000000,€0
0.0000000,€0
0.0000000,€0
0.0000000,€0

In [171]:
-- Updating Values with K
UPDATE [PortfolioProject].[dbo].[fifa21_clean_data] 
SET Value_M_E = CASE 
        WHEN Value_M_E LIKE '%[^0-9.]%' 
        THEN CAST(SUBSTRING(Value_M_E, 1, LEN(Value_M_E)-1) AS DECIMAL(10,2))/1000
        ELSE CAST(Value_M_E AS DECIMAL(10,2))
    END

## Formatting Wage as Float, by removing "€", "M" and "K"

In [172]:
-- Removing Euro an K sign from Wage and changing format
SELECT TOP(10)
  CASE 
    WHEN CHARINDEX('K', Wage) > 0 
      THEN SUBSTRING(Wage, 2, CHARINDEX('K', Wage)-2)
    WHEN CHARINDEX('€', Wage) = 1
      THEN SUBSTRING(Wage, 2, LEN(Wage)-1)
    ELSE NULL 
  END,
  Wage
FROM 
  [PortfolioProject].[dbo].[fifa21_clean_data];

(No column name),Wage
13,€13K
12,€12K
50,€50K
41,€41K
44,€44K
44,€44K
16,€16K
48,€48K
25,€25K
25,€25K

In [173]:
-- Adding Wage_M_E Column to table
ALTER TABLE [PortfolioProject].[dbo].[fifa21_clean_data]
ADD Wage_M_E FLOAT;

In [174]:
-- Setting Wage_M_E values
UPDATE [PortfolioProject].[dbo].[fifa21_clean_data]
SET Wage_M_E  = CASE 
    WHEN CHARINDEX('K', Wage) > 0 
      THEN SUBSTRING(Wage, 2, CHARINDEX('K', Wage)-2)
    WHEN CHARINDEX('€', Wage) = 1
      THEN SUBSTRING(Wage, 2, LEN(Wage)-1)
    ELSE NULL 
  END

In [175]:
-- Formatting Wage_M_E as FLOAT
SELECT TOP(10) Wage_M_E, CAST(Wage_M_E AS FLOAT)
FROM [PortfolioProject].[dbo].[fifa21_clean_data]
ORDER BY Wage_M_E DESC

Wage_M_E,(No column name)
950,950
950,950
950,950
950,950
950,950
950,950
950,950
950,950
950,950
950,950

In [176]:
-- Setting Type as FLOAT
UPDATE [PortfolioProject].[dbo].[fifa21_clean_data]
SET Wage_M_E = CAST(Wage_M_E AS FLOAT)

## Formatting Release\_Clause as Float, by removing "€", "M" and "K"

In [181]:
-- Removing Euro an M sign from Release_Clause
SELECT TOP(10)
  CASE 
    WHEN CHARINDEX('M', Release_Clause) > 0 
      THEN SUBSTRING(Release_Clause, 2, CHARINDEX('M', Release_Clause)-2)
    WHEN CHARINDEX('€', Release_Clause) = 1
      THEN SUBSTRING(Release_Clause, 2, LEN(Release_Clause)-1)
    ELSE NULL 
  END,
  Release_Clause
FROM 
  [PortfolioProject].[dbo].[fifa21_clean_data];

(No column name),Release_Clause
18.9,€18.9M
16.5,€16.5M
17.9,€17.9M
13.6,€13.6M
15.3,€15.3M
17,€17M
21,€21M
20,€20M
17.9,€17.9M
17.9,€17.9M

In [182]:
-- Adding Column Release_Clause_M_E
ALTER TABLE [PortfolioProject].[dbo].[fifa21_clean_data]
ADD Release_Clause_M_E VARCHAR(50);

In [183]:
-- Setting Release_Clause_M_E values
UPDATE [PortfolioProject].[dbo].[fifa21_clean_data]
SET Release_Clause_M_E  = CASE 
    WHEN CHARINDEX('M', Release_Clause) > 0 
      THEN SUBSTRING(Release_Clause, 2, CHARINDEX('M', Release_Clause)-2)
    WHEN CHARINDEX('€', Release_Clause) = 1
      THEN SUBSTRING(Release_Clause, 2, LEN(Release_Clause)-1)
    ELSE NULL 
  END

In [184]:
-- Looking at Release Clause columns
SELECT TOP(10) Release_Clause_M_E, Release_Clause
FROM [PortfolioProject].[dbo].[fifa21_clean_data]
ORDER BY Release_Clause_M_E DESC

-- Next step is to remove K

Release_Clause_M_E,Release_Clause
9K,€9K
99K,€99K
99K,€99K
99K,€99K
999K,€999K
999K,€999K
999K,€999K
999K,€999K
999K,€999K
999K,€999K

In [185]:
-- To remove K we take the first value from the left where value is not numeric (Where there is a string)
SELECT TOP(10) Release_Clause_M_E, LEFT(Release_Clause_M_E, LEN(Release_Clause_M_E) - 1)
FROM [PortfolioProject].[dbo].[fifa21_clean_data]
WHERE ISNUMERIC(Release_Clause_M_E) = 0
ORDER BY Release_Clause_M_E DESC

Release_Clause_M_E,(No column name)
9K,9
99K,99
99K,99
99K,99
999K,999
999K,999
999K,999
999K,999
999K,999
999K,999

In [186]:
-- Setting New Values for where, ISNUMERIC(Release_Clause_M_E) = 0
UPDATE [PortfolioProject].[dbo].[fifa21_clean_data]
SET Release_Clause_M_E = LEFT(Release_Clause_M_E, LEN(Release_Clause_M_E) - 1)
WHERE ISNUMERIC(Release_Clause_M_E) = 0

In [187]:
-- Accounting for values with M 
SELECT  TOP(10) Release_Clause, 
    CASE 
        WHEN Release_Clause LIKE '%K%' 
        THEN CAST(SUBSTRING(Release_Clause_M_E, 1, LEN(Value_M_E)-1) AS DECIMAL(10,2))/1000
        ELSE CAST(Release_Clause_M_E AS DECIMAL(10,2))
    END AS Release_Clause_M_E
FROM 
    [PortfolioProject].[dbo].[fifa21_clean_data]
ORDER BY 
    Release_Clause_M_E DESC

Release_Clause,Release_Clause_M_E
€203.1M,203.1000000
€166.5M,166.5000000
€161M,161.0000000
€159.4M,159.4000000
€147.7M,147.7000000
€145.3M,145.3000000
€144.3M,144.3000000
€144.3M,144.3000000
€140.2M,140.2000000
€139.6M,139.6000000

In [188]:
-- Setting Release Clause value
UPDATE [PortfolioProject].[dbo].[fifa21_clean_data]
SET Release_Clause_M_E = CASE 
        WHEN Release_Clause LIKE '%K%' 
        THEN CAST(SUBSTRING(Release_Clause_M_E, 1, LEN(Value_M_E)-1) AS DECIMAL(10,2))/1000
        ELSE CAST(Release_Clause_M_E AS DECIMAL(10,2))
    END

In [189]:
-- Formatting Release Clause as FLOAT
UPDATE [PortfolioProject].[dbo].[fifa21_clean_data]
SET Release_Clause_M_E = CAST(Release_Clause_M_E AS FLOAT)

### Formatting W\_F as INT

In [190]:
-- Removing " *" sign from W_F
SELECT TOP(10) W_F, LEFT(W_F, 1)
FROM [PortfolioProject].[dbo].[fifa21_clean_data]

W_F,(No column name)
3 ★,3
3 ★,3
4 ★,4
2 ★,2
3 ★,3
2 ★,2
3 ★,3
3 ★,3
3 ★,3
3 ★,3

In [191]:
ALTER TABLE [PortfolioProject].[dbo].[fifa21_clean_data]
ADD W_F_new INT;

In [192]:
UPDATE [PortfolioProject].[dbo].[fifa21_clean_data]
SET W_F_new  = LEFT(W_F, 1)

### Formatting SM as INT

In [193]:
-- Removing "*" sign SM
SELECT TOP(10) SM, LEFT(SM, 1)
FROM [PortfolioProject].[dbo].[fifa21_clean_data]

SM,(No column name)
3★,3
3★,3
4★,4
3★,3
2★,2
3★,3
3★,3
4★,4
3★,3
2★,2

In [194]:
ALTER TABLE [PortfolioProject].[dbo].[fifa21_clean_data]
ADD SM_new INT;

In [195]:
UPDATE [PortfolioProject].[dbo].[fifa21_clean_data]
SET SM_new  = LEFT(SM, 1)

### Formatting IR as INT

In [196]:
-- Removing " *" from IR
SELECT TOP(10) IR, LEFT(IR, 1)
FROM [PortfolioProject].[dbo].[fifa21_clean_data]

IR,(No column name)
2 ★,2
1 ★,1
2 ★,2
2 ★,2
2 ★,2
2 ★,2
1 ★,1
1 ★,1
2 ★,2
1 ★,1

In [197]:
ALTER TABLE [PortfolioProject].[dbo].[fifa21_clean_data]
ADD IR_new INT;

In [198]:
UPDATE [PortfolioProject].[dbo].[fifa21_clean_data]
SET IR_new  = LEFT(IR, 1)

### Formatting Hits as INT

In [199]:
-- Removing first character from Hits
SELECT TOP(10) Hits, RIGHT(Hits, LEN(Hits)-1)
FROM [PortfolioProject].[dbo].[fifa21_clean_data]

Hits,(No column name)
25,25
37,37
25,25
9,9
29,29
21,21
41,41
62,62
9,9
3,3

In [201]:
ALTER TABLE [PortfolioProject].[dbo].[fifa21_clean_data]
ADD Hits_new VARCHAR(50);

: Msg 2705, Level 16, State 4, Line 1
Column names in each table must be unique. Column name 'Hits_new' in table 'PortfolioProject.dbo.fifa21_clean_data' is specified more than once.

In [202]:
UPDATE [PortfolioProject].[dbo].[fifa21_clean_data]
SET Hits_new  = RIGHT(Hits, LEN(Hits)-1)

In [203]:
--Formatting Hits_new as INT. 
SELECT TOP(10) Hits_new
FROM [PortfolioProject].[dbo].[fifa21_clean_data]
ORDER BY Hits_new

Hits_new
1
1
1
1
1
1
1
1
1
1

In [204]:
SELECT TOP(10) Hits_new, LEFT(Hits_new, LEN(Hits_new) - 1)
FROM [PortfolioProject].[dbo].[fifa21_clean_data]
WHERE ISNUMERIC(Hits_new) = 0;

-- There was a mistake in the computation of hit. It shouldn't have K nor be a FLOAT type

Hits_new,(No column name)
1.2K,1.2
1.7K,1.7
1.1K,1.1
1.3K,1.3
4.5K,4.5
1.3K,1.3
1.9K,1.9
1.8K,1.8
1.1K,1.1
1.9K,1.9

In [205]:
UPDATE [PortfolioProject].[dbo].[fifa21_clean_data]
SET Hits_new = LEFT(Hits_new, LEN(Hits_new) - 1)
WHERE ISNUMERIC(Hits_new) = 0;

In [206]:
UPDATE [PortfolioProject].[dbo].[fifa21_clean_data]
SET Hits_new = CAST(Hits_new AS FLOAT)

--NOTE: the variable should be an INT but there are misspells

### Formatting Loan\_Date\_End as Date

In [207]:
-- Formatting Loan_Date_End as Date
SELECT TOP(10) Loan_Date_End
FROM [PortfolioProject].[dbo].[fifa21_clean_data]
WHERE Loan_Date_End = 'N/A'

Loan_Date_End
N/A
N/A
N/A
N/A
N/A
N/A
N/A
N/A
N/A
N/A

In [208]:
-- Accounting for strings 'N/A'
SELECT TOP(10)
  CASE 
  WHEN Loan_Date_End = 'N/A' THEN ''
  ELSE CAST(Loan_Date_End AS DATE) 
  END AS Loan_Date_End_formatted
FROM [PortfolioProject].[dbo].[fifa21_clean_data];

Loan_Date_End_formatted
1900-01-01
1900-01-01
1900-01-01
1900-01-01
1900-01-01
1900-01-01
1900-01-01
1900-01-01
1900-01-01
1900-01-01

In [209]:
UPDATE [PortfolioProject].[dbo].[fifa21_clean_data]
SET Loan_Date_End = CASE 
  WHEN Loan_Date_End = 'N/A' THEN ''
  ELSE CAST(Loan_Date_End AS DATE) 
  END

In [210]:
-- Setting out of range values as Null
UPDATE [PortfolioProject].[dbo].[fifa21_clean_data]
SET Loan_Date_End = NULL
WHERE YEAR(Loan_Date_End) < 2000

### Creating Final Table

From this table will drop the unecessary Columns

In [ ]:
-- Creating Table
SELECT *
INTO [PortfolioProject].[dbo].[fifa21_data]
FROM [PortfolioProject].[dbo].[fifa21_clean_data]

# Data Analysis

**Objectives**

- Identify the top-performing players. 
- Analyze the relationship between player attributes and overall rating.

## Top 10 Players by Overall Rating

In [33]:
SELECT TOP 10 [LongName], [Nationality], [Position1], [Team], OVA 
FROM [PortfolioProject].[dbo].[fifa21_data]
ORDER BY [OVA] DESC

LongName,Nationality,Position1,Team,OVA
Lionel Messi,Argentina,RW,FC Barcelona,93
C. Ronaldo dos Santos Aveiro,Portugal,ST,Juventus,92
Jan Oblak,Slovenia,GK,Atlético Madrid,91
Kevin De Bruyne,Belgium,CAM,Manchester City,91
Neymar da Silva Santos Jr.,Brazil,LW,Paris Saint-Germain,91
Robert Lewandowski,Poland,ST,FC Bayern München,91
Kylian Mbappé,France,ST,Paris Saint-Germain,90
Alisson Ramses Becker,Brazil,GK,Liverpool,90
Mohamed Salah,Egypt,RW,Liverpool,90
Sadio Mané,Senegal,LW,Liverpool,90

### Highlights

- Lionel Messi and Cristiano Ronaldo are the top two players with ratings of 93 and 92 respectively. 
- The top 10 includes players from various positions, including RW, ST, GK, CAM, and LW. 
- Players from popular clubs like FC Barcelona, Juventus, Paris Saint-Germain, Manchester City, and Liverpool are included in the top 10. 
- The top 10 includes players from different countries, such as Argentina, Portugal, Slovenia, Belgium, Brazil, Poland, France, Egypt, and Senegal.

## Top 10 Players by Potential

In [40]:
SELECT TOP 10 [LongName], [Nationality], [Position1], [Team], POT, Age, OVA 
FROM [PortfolioProject].[dbo].[fifa21_data]
ORDER BY POT DESC

LongName,Nationality,Position1,Team,OVA,POT,Age
Kylian Mbappé,France,ST,Paris Saint-Germain,90,95,21
Lionel Messi,Argentina,RW,FC Barcelona,93,93,33
Jan Oblak,Slovenia,GK,Atlético Madrid,91,93,27
Marc-André ter Stegen,Germany,GK,FC Barcelona,90,93,28
Jadon Sancho,England,RM,Borussia Dortmund,87,93,20
Kai Havertz,Germany,CAM,Chelsea,85,93,21
João Félix Sequeira,Portugal,CF,Atlético Madrid,81,93,20
Vinícius José de Oliveira Júnior,Brazil,LW,Real Madrid,80,93,19
C. Ronaldo dos Santos Aveiro,Portugal,ST,Juventus,92,92,35
Trent Alexander-Arnold,England,RB,Liverpool,87,92,21

### Highlights

- Kylian Mbappé has a high potential rating of 95 and is only 21 years old, suggesting that he has significant room for growth and development. 
- Lionel Messi may be considered one of the best players in the world with an OVA rating of 93 at 33 years old. 
- Jan Oblak and Marc-André ter Stegen are highly-rated goalkeepers with OVA ratings of 91 and 90, respectively, and a potential rating of 93. 
- Jadon Sancho, Kai Havertz, and João Félix Sequeira have high potential ratings of 93, indicating that they have the potential to become elite players. 
- Vinícius José de Oliveira Júnior is a young player at 19 years old with a high potential rating of 93. 
- C. Ronaldo dos Santos Aveiro is an experienced player at 35 years old but still maintains a high OVA rating of 92. 
- Trent Alexander-Arnold is a young and highly-rated right-back with a high potential rating of 92.

## Top 20 Players by Attacking Attribute

In [47]:
SELECT TOP (20) [LongName], [Position1], Age, Attacking, OVA 
FROM [PortfolioProject].[dbo].[fifa21_data]
ORDER BY Attacking DESC

LongName,Position1,Age,Attacking,OVA
C. Ronaldo dos Santos Aveiro,ST,35,437,92
Lionel Messi,RW,33,429,93
Luis Suárez,ST,33,429,87
Karim Benzema,CF,32,426,89
Antoine Griezmann,ST,29,425,87
Robert Lewandowski,ST,31,423,91
Harry Kane,ST,26,420,88
Thomas Müller,CAM,30,419,86
Gareth Bale,RW,30,417,83
Sergio Agüero,ST,32,411,89
Sadio Mané,LW,28,410,90
James Rodríguez,CAM,28,409,82
Neymar da Silva Santos Jr.,LW,28,408,91
Kylian Mbappé,ST,21,408,90
Iago Aspas Juncal,ST,32,408,84
Kevin De Bruyne,CAM,29,407,91
Gerard Moreno Balagueró,ST,28,406,83
Paulo Dybala,CF,26,405,88
Raúl Jiménez,ST,29,405,84
Pierre-Emerick Aubameyang,ST,31,403,87

### Highlights

- The top two players, Ronaldo and Messi, have high attacking ratings and overall ratings, indicating that they are strong attackers and are well-rounded players overall. 
- Some players on the list have higher attacking ratings than their overall ratings, such as Luis Suarez, Antoine Griezmann, and Sergio Aguero. This suggests that they are strong attackers but may not excel as much in other areas. 
- Robert Lewandowski, Harry Kane, and Kylian Mbappe are all highly rated attackers and have relatively high overall ratings as well, indicating that they are strong all-around players. 
- It is worth noting that some players who are primarily midfielders or wingers also appear on this list, such as Thomas Muller, Kevin De Bruyne, and Neymar Jr. This suggests that they contribute significantly to their team's attacking efforts. 
- Finally, it is interesting to see some players on this list who may not be as well-known or highly rated overall, such as Iago Aspas Juncal and Gerard Moreno Balaguero. This highlights the importance of looking at individual attributes rather than just overall ratings when assessing a player's strengths and weaknesses.

## Top 20 Players by Finishing Attribute

In [48]:
SELECT TOP (20) [LongName], [Position1], Age, Finishing, OVA 
FROM [PortfolioProject].[dbo].[fifa21_data]
ORDER BY Finishing DESC

LongName,Position1,Age,Finishing,OVA
Lionel Messi,RW,33,95,93
C. Ronaldo dos Santos Aveiro,ST,35,95,92
Robert Lewandowski,ST,31,94,91
Sergio Agüero,ST,32,94,89
Harry Kane,ST,26,94,88
Ciro Immobile,ST,30,93,87
Luis Suárez,ST,33,92,87
Jamie Vardy,ST,33,92,86
Kylian Mbappé,ST,21,91,90
Mohamed Salah,RW,28,91,90
Pierre-Emerick Aubameyang,ST,31,91,87
Sadio Mané,LW,28,90,90
Mauro Icardi,ST,27,90,85
Iago Aspas Juncal,ST,32,89,84
Karim Benzema,CF,32,88,89
Antoine Griezmann,ST,29,88,87
Timo Werner,ST,24,88,85
Wissam Ben Yedder,ST,29,88,84
Duván Zapata,ST,29,88,83
Gerard Moreno Balagueró,ST,28,88,83

### Highlight

It seems that there are some players who consistently perform well in terms of finishing, regardless of their age. Lionel Messi and C. Ronaldo dos Santos Aveiro are the top two players in terms of finishing, with both having a rating of 95 out of 100. 

Robert Lewandowski and Sergio Agüero are also among the top finishers with 94 out of 100. 

It is interesting to note that the age of the player does not seem to have a significant impact on their finishing ability, as some of the top performers such as Messi, C. Ronaldo, Lewandowski, and Suárez are all over 30 years old.

## Top 20 Players by Strength Attribute

In [50]:
SELECT TOP (20) [LongName], [Position1], Age, Strength, OVA 
FROM [PortfolioProject].[dbo].[fifa21_data]
ORDER BY Strength DESC

LongName,Position1,Age,Strength,OVA
Adebayo Akinfenwa,ST,38,97,65
Daryl Dike,ST,20,96,63
Armando Méndez,RB,24,95,71
Aleksandar Vukotić,CB,24,95,68
Romelu Lukaku,ST,27,95,85
Joyskim Dawa Tchakonte,CB,24,95,66
Pape Abou Cissé,CB,24,94,75
Tomáš Petrášek,CB,28,94,67
Stefan Maierhofer,ST,37,94,64
Obbi Oularé,ST,24,94,71
Florian Ballas,CB,27,94,68
Felipe Carvalho,CB,26,94,68
Uche Ikpeazu,ST,25,94,64
Kalidou Koulibaly,CB,29,94,88
Sebastián Coates,CB,29,94,81
Geoffrey Kondogbia,CM,27,94,79
Jhon Monsario,CB,35,93,76
Yeimar Gómez Andrade,CB,28,93,76
Graziano Pellè,ST,34,93,75
Luke DeVere,CB,30,93,67

### Highlight

- One key takeaway from analyzing strength is that it is not necessarily correlated with a player's overall rating. Some players, like Adebayo Akinfenwa and Daryl Dike, have extremely high strength ratings but relatively low overall ratings. 
- It is also notable that some of the players with high strength ratings are defenders, like Armando Méndez and Kalidou Koulibaly, while others are forwards, like Romelu Lukaku and Obbi Oularé. This suggests that strength can be an important attribute for players in different positions, depending on their role and playing style. 
- Finally, it's worth noting that strength is not the only important attribute for players, and players with high strength ratings may not necessarily be the most effective or desirable players in the game. Other attributes, like finishing and dribbling, can be just as important, if not more so, for certain positions and play styles.

## Top 20 Players by Defending Attribute

In [51]:
SELECT TOP (20) [LongName], [Position1], Age, Defending, OVA 
FROM [PortfolioProject].[dbo].[fifa21_data]
ORDER BY Defending DESC

LongName,Position1,Age,Defending,OVA
Virgil van Dijk,CB,28,272,90
Giorgio Chiellini,CB,35,272,87
Kalidou Koulibaly,CB,29,267,88
Aymeric Laporte,CB,26,266,87
N'Golo Kanté,CDM,29,264,88
Mats Hummels,CB,31,264,86
Sergio Ramos García,CB,34,263,89
Raphaël Varane,CB,27,262,86
Milan Škriniar,CB,25,262,85
Toby Alderweireld,CB,31,262,85
Marcos Aoás Corrêa,CB,26,261,85
Wilfred Ndidi,CDM,23,261,84
José María Giménez,CB,25,261,84
Allan Marques Loureiro,CM,29,261,83
Raúl Albiol Tortajada,CB,34,261,82
Diego Godín,CB,34,260,85
Niklas Süle,CB,24,260,84
Stefan de Vrij,CB,28,260,84
Carlos Henrique Venancio Casimiro,CDM,28,259,89
Francesco Acerbi,CB,32,259,83

### Highlight

Center backs dominate the list: 18 out of the 20 players on the list are center backs. This highlights the importance of strong center backs in defense. 

Age is not a limiting factor: While there are some older players on the list, such as Giorgio Chiellini and Diego Godin, many of the top defenders are in their mid to late twenties, indicating that age does not limit a player's ability to defend in the game. 

Defensive midfielders also have high defending attributes: N'Golo Kante and Allan Marques Loureiro are both midfielders who have high defending attributes, showing that midfielders who can defend well are also valuable in FIFA 21. Overall rating is not necessarily correlated with defending ability: While some of the players on the list have high overall ratings, such as Virgil van Dijk and Sergio Ramos, others have lower overall ratings, such as Stefan de Vrij and Francesco Acerbi. 

This suggests that a player's overall rating is not necessarily a reliable indicator of their defensive ability.

## Analysis Summary

The exploratory analysis reveals several facets of FIFA 21's player ratings. Lionel Messi and Cristiano Ronaldo are the top two players with high ratings, while the top 10 list includes players from different positions, teams, and nations. Young athletes with high potential ratings, like as Kylian Mbappé and Vincius José de Oliveira Junior, have the potential to develop into elite athletes. Nevertheless, regardless of their age, some players, such as Messi and Ronaldo, constantly deliver strong finishing performances. Age should not be a barrier when highlighting the value of strong center backs in defense. A player's total rating is not always a good predictor of their defensive skill, it is also noted that defensive midfielders can have high defensive qualities. In the end, it is

# Conclusion

In conclusion, studying the best FIFA 21 players offers intriguing details about various qualities and playing positions. While center backs and defensive midfielders are important positions for a solid defense, Lionel Messi and C. Ronaldo dos Santos Aveiro are the greatest finishers regardless of age. Strength is not always associated with overall ranking. A player's ability to defend in the game is not constrained by their age, and their overall rating is not necessarily a good indication of their defensive prowess. These results emphasize the significance of comprehending the distinctive qualities and player roles in the FIFA 21 game.

# FIFA 21 Dashboard

link here -\> https://public.tableau.com/app/profile/ramberto.jr.sosa.cueto/viz/FIFA21Dashboard/FIFA21Dashboard?publish=yes